### ISSUE TITLE
[Practice 7][Google Chrome][API] Status is 200 instead of 400 when New Password contain space character

### ISSUE THREAD

**Issue by at-hoatran** [queenscity/internship-2019-summer-fall#28]
**Environment test**
- Stg
- Browser: Chrome 75.0.3770.100
- Device: Laptop (Windows 10)
- Deploy at 2019/09/18
- Testing time: 2019/09/19 03:52 PM

**Pre_condition**
1. Open My Profile page
2. Open Change Password
form

**Steps to perform**
1. Input invalid data into New Password field contain space character
(Eg: "thanh HOA12@#") 
2. Input valid data into remain fields
3. Click on Submit button
4. Check calling API 
5. Check API response

**Actual results**
- At step 3: There is successfully message "Your password have changed successfully." is displayed in alert
- At step 4: Call API POST (api/v2/users/password)
- At step 5: Status is 200 OK

**Expected results**
- At step 3: "Must contain at least 8 characters (including a digit, an upper case character and a symbol)." message is displayed in alert
- At step 4: Call API POST (api/v2/users/password)
- At step 5: Status is 400 Bad Request and response body is displayed correctly

**Account testing**
- Email: 
- Password: 
- URL:

**Comment by at-hoatran** [comment]
Bug is duplicate. Can track bug with https://github.com/queenscity/internship-2019-summer-fall/issues/8
Thank you!

**Comment by at-quynhnguyen** [comment]
@at-hoatran 
Yes Hoa, I'll close this. Thank you!!
