### ISSUE TITLE
[Practice 7][Google Chrome][API] Status is 200 instead of 400 when New Password is same with Current Password 

### ISSUE THREAD

**Issue by at-hoatran** [queenscity/internship-2019-summer-fall#30]
**Environment test**
- Stg
- Browser: Chrome 75.0.3770.100
- Device: Laptop (Windows 10)
- Deploy at 2019/09/18
- Testing time: 2019/09/19 04:24 PM

**Pre_condition**
1. Open My Profile page
2. Open Change Password
form

**Steps to perform**
1. Input valid data into Current Password field
2. Input data into New Password field and Confirm Password field is same Current Password field
3. Click on Submit button
4. Check calling API 
5. Check API response

**Actual results**
- At step 3: There is successfully message "Your password have changed successfully." is displayed in alert
- At step 4: Call API POST (api/v2/users/password)
- At step 5: Status is 200 OK

**Expected results**
- At step 3: "New password is different Current password." message is displayed in alert
- At step 4: Call API POST (api/v2/users/password)
- At step 5: Status is 400 Bad Request and response body is displayed correctly

**Account testing**
- Email: 
- Password: 
- URL:

**Comment by at-hoatran** [comment]
Bug is duplicate. Can track bug with https://github.com/queenscity/internship-2019-summer-fall/issues/12
Thank you!

**Comment by at-quynhnguyen** [comment]
@at-hoatran 
Ok, so I'll close this. Thanks for your explaining!!
